SDP/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from SE import settings

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^instructor/$', views.instructor),
	url(r'^instructor/ins-course/(?P<course_id>\d+)/(?P<module_id>\d+)$', views.instructorcourse),
	url(r'^instructor/addcourse$', views.instructorcoursenew),
	url(r'^instructor/ins-course/addnewmodule/(?P<course_id>\d+)$',views.addnewModule),
	url(r'^instructor/ins-course/addcourse$',views.addnewCourse),
	url(r'^instructor/ins-course/(?P<module_id>\d+)/addcomponent$',views.addnewComponent),
	url(r'^instructor/ins-course/(?P<course_id>\d+)/editname$',views.editcoursename),
	url(r'^instructor/ins-course/(?P<course_id>\d+)/editdescription$',views.editcoursedesc),
	url(r'^instructor/ins-course/(?P<course_id>\d+)/editcat$',views.editcoursecat),
	url(r'^instructor/ins-course/(?P<module_id>\d+)/editmodule$',views.editmodule),
	url(r'^instructor/ins-course/(?P<component_id>\d+)/editcomponent$',views.editcomponent),
	url(r'^mycourse/(?P<course_id>[0-9]+)/module/(?P<module_id>[0-9]+)/$', views.mycourse, name='mycourse'),
	url(r'^history/(?P<course_id>[0-9]+)/module/(?P<module_id>[0-9]+)/$', views.history, name='history'),
	url(r'^enroll/(?P<course_id>[0-9]+)/$', views.enroll, name='enroll'),
	url(r'^drop/(?P<course_id>[0-9]+)/$', views.drop, name='drop'),
	url(r'^add/(?P<course_id>[0-9]+)/$', views.add, name='add'),
	url(r'^retake/(?P<course_id>[0-9]+)/$', views.retake, name='retake'),
	url(r'^finish/(?P<course_id>[0-9]+)/(?P<module_id>[0-9]+)/$', views.finish, name='finish'),
	url(r'^login', views.login_view, name="login" ),  
    url(r'^logout/$', views.logout_view, name="logout" ),  
    url(r'^hr/$', views.all_participants),
    url(r'^attemptlogin',views.attempt_login),  
    url(r'^login_incorrect',views.login_incorrect),
    url(r'^inst-course/delete/(?P<course_id>\d+)$', views.deleteCourse),
    url(r'^inst-course/publish/(?P<course_id>\d+)$', views.publishCourse),
    url(r'^inst-course/deletecomponent/(?P<c_id>\d+)$', views.deleteComponent),
    url(r'^inst-course/deletemodule/(?P<m_id>\d+)$', views.deleteModule),
    url(r'^instructor/ins-course/movemoddown/(?P<id>\d+)$', views.mdown),
    url(r'^instructor/ins-course/movemodup/(?P<id>\d+)$', views.mup),
    url(r'^instructor/ins-course/movecompup/(?P<id>\d+)$', views.cup),
    url(r'^instructor/ins-course/movecompdown/(?P<id>\d+)$', views.cdown),
    url(r'^administrator/$', views.administrator_view),
    url(r'^assigninstructor/(?P<username>\d+)/$', views.add_instructor_view),
    url(r'^register', views.register),
    url(r'^attemptregister',views.attmeptregister),
] 

SE/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
	url(r'^SDP/', include('SDP.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^SDP/', include('SDP.urls')),
    url(r'^admin/', admin.site.urls),
]

SDP/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# class Author(models.Model):
# 	name = models.CharField(max_length=200)



# class Article(models.Model):
# 	author = models.ForeignKey(Author, on_delete=models.CASCADE)
# 	title = models.CharField(max_length=200)
# 	content = models.TextField()
# 	tags = models.ManyToManyField(Tag)
class RightsSupport(models.Model):
	class Meta:

		managed = False  # No database table creation or deletion operations \
						# will be performed for this model. 

		permissions = ( 
			('instructor', 'Instructor'),  
			('admin', 'Admin'), 
		)

class Category(models.Model):
	name = models.CharField(max_length=200)
	def __str__(self):
		return self.name

class Course(models.Model):
	name = models.CharField(max_length=200)
	course_detail = models.TextField()
	OPEN = 'OP'
	DRAFT = 'DR'
	CLOSED = 'CL'
	STATUS_CHOICES = (
		(OPEN, 'Open'),
		(DRAFT, 'Draft'),
		(CLOSED, 'Closed'),
	)
	status = models.CharField(
		max_length=2,
		choices = STATUS_CHOICES,
		default = DRAFT,
	)
	category = models.ForeignKey(Category) 
	instructor =  models.ForeignKey(User)
	def __str__(self):
		return self.name 

class Module(models.Model):
	name = models.CharField(max_length=200)
	sequence = models.IntegerField()
	course = models.ForeignKey(Course, on_delete=models.CASCADE)   
	def __str__(self):
		return self.name 

class Component(models.Model):
	name = models.CharField(max_length=200)
	TEXT = 'TX'
	IMAGE = 'IM'
	VIDEO = 'VD'
	FILE = 'FL'
	TYPE_CHOICES = (
		(TEXT, 'Text'),
		(IMAGE, 'Image'),
		(VIDEO, 'Video'),
		(FILE, 'File'),
	)
	typ = models.CharField(
		max_length=2,
		choices = TYPE_CHOICES,
		default = TEXT,
	)
	content = models.TextField()
	sequence = models.IntegerField()
	module = models.ForeignKey(Module, on_delete=models.CASCADE)

class CourseParticipantMap(models.Model):
	participant =  models.ForeignKey(User) 
	course =  models.ForeignKey(Course)
	progress = models.CharField(max_length=200)

SDP/forms.py
from django import forms  
from django.contrib.auth import(
		authenticate,
		get_user_model,
		login,
		logout
	)
from django.contrib import auth
from django.contrib.auth.models import User

User = get_user_model()

class UserLoginForm(forms.Form):  
    username = forms.CharField()      
    password = forms.CharField(widget=forms.PasswordInput)  

    def clean(self, *args, **kwargs):

    	if self.cleaned_data.get("username") and self.cleaned_data.get("password"):
    		user = authenticate(username=self.cleaned_data.get("username"), passowrd=self.cleaned_data.get("password"))
    		print (user)
	    	if not user:
	    		raise forms.ValidationError("The user does not exist")
	    	if not user.check_password(password):
	    		raise forms.ValidationError("Incorrect password")
	    	return super(UserLoginForm, self).clean(*args, **kwargs)

class UserRegisterForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)
	email = forms.EmailField()
	firstname = forms.CharField(label='First Name')
	lastname = forms.CharField(label='Last Name')

	def clean(self):
		if User.objects.filter(username = self.cleaned_data.get("username")).exists():
			raise forms.ValidationError("Username already taken")

    

SDP/views.py
from django.shortcuts import render
from django.http import Http404
from django.shortcuts import render_to_response
from django.template import loader
from django.contrib.auth.models import User,Permission
from django.db import models
from .models import Course
from .models import Module
from .models import Category
from .models import Component
from .models import CourseParticipantMap
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.db.models import Max
from django.urls import reverse
from django.views import generic
from django.contrib.auth.models import User, Group
from django import forms  
from django.shortcuts import render, redirect
from django.contrib import auth 
from django.contrib.auth import authenticate, get_user_model, login,logout 
from .forms import UserLoginForm, UserRegisterForm
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType


# Create your views here.

from django.http import HttpResponse,HttpResponseRedirect

from django.contrib.auth.decorators import permission_required





def login_view(request):
	template = loader.get_template('login.html')
	context = {
	}
	return HttpResponse(template.render(context, request))

def attempt_login(request):
	uname = request.POST.get('username')
	pwd = request.POST.get('pwd')
	user = authenticate(username=uname, password=pwd)
	if user is not None:
		login(request, user)
		URL = "/SDP/mycourse/0/module/0/"
		if user.has_perm('SDP.admin'):
			URL = "/SDP/administrator/"
		elif user.has_perm('SDP.instructor'):
			URL = "/SDP/instructor/"
	else:
		URL = "/SDP/login_incorrect"
	    # No backend authenticated the credentials

	return HttpResponseRedirect(URL)

def login_incorrect(request):
	template = loader.get_template('login_error.html')
	context = {
	}
	return HttpResponse(template.render(context, request))

@login_required(login_url='/SDP/login')
def all_participants(request):
	user = User.objects.filter(groups__name='Participant')
	return render(request, "hr.html", {"user" :user})
	
def logout_view(request):
	logout(request)
	return redirect('/SDP/login')

def index(request):
	return redirect('/SDP/login')
#user =  Users.objects.get(pk=user_id)

@login_required(login_url='/SDP/login')
@permission_required('SDP.instructor')
def instructor(request):

	user = request.user
	template = loader.get_template('instructor.html')
	courses = Course.objects.filter(instructor=user)
	for c in courses:
		if c.status == 'DR':
			c.status = "Draft"
		elif c.status == 'OP':
			c.status = "Open"
		elif c.status == 'CL': 
			c.status = "Closed" 
	context = {
		'courses': courses,
	}
	return HttpResponse(template.render(context, request))
	
@login_required(login_url='/SDP/login')
@permission_required('SDP.instructor')
def instructorcourse(request,course_id,module_id):

	course = Course.objects.get(pk=course_id)
	template = loader.get_template('instructor-course.html')
	if course.status == 'DR':
		course.status = "Draft"
	elif course.status == 'OP':
		course.status = "Open"
	elif course.status == 'CL': 
		course.status = "Closed"
	module = Module.objects.filter(course=course).order_by("sequence")
	
	print (module)
	
	cat = Category.objects.all()
	module_pass = get_object_or_404(module,course=course_id,sequence=module_id)
	comp = Component.objects.filter(module=module_pass).order_by("sequence")
	for c in comp:
		if c.typ == "VD":
			c.typ = "Video"
		elif c.typ == "IM":
			c.typ = "Image"
		elif c.typ == "TX":
			c.typ = "Text"
		elif c.typ == "FL":
			c.typ = "File"
	context = {
		'course': course,
		'modules':module,
		'components':comp,
		'cmodule':module_pass,	
		'categories': cat,

	}
	return HttpResponse(template.render(context, request))

@login_required(login_url='/SDP/login')
@permission_required('SDP.instructor')
def instructorcoursenew(request):

	template = loader.get_template('instructor-course-new.html')

	cat = Category.objects.all()
	context = {
		'categories': cat,
	}
	return HttpResponse(template.render(context, request))

@login_required(login_url='/SDP/login')
@permission_required('SDP.instructor')
def addnewModule(request,course_id):

		post_text = request.POST.get('add-module-name')
		if(post_text==""):
			return HttpResponseRedirect('/SDP/instructor/ins-course/'+str(course_id)+'/1')
		post_id = course_id
		response_data = {}
		args = Module.objects.filter(course=Course.objects.get(pk=post_id))
		# Calculates the maximum out of the already-retrieved objects
		s = Module.objects.filter(course=Course.objects.get(pk=post_id)).aggregate(Max('sequence'))['sequence__max']
		sec = s+1
		module = Module(name=post_text, course=Course.objects.get(pk=post_id), sequence=sec)
		module.save()

		return HttpResponseRedirect('/SDP/instructor/ins-course/'+str(course_id)+'/'+str(module.sequence))

@login_required(login_url='/SDP/login')
@permission_required('SDP.instructor')
def addnewCourse(request):
	cname = request.POST.get('coursename')
	des = request.POST.get('description')
	cat = request.POST.get('cat')
	mname = request.POST.get('modulename')

	if((cname=="")and(mname=="")and(des=="")and(cat=="")):
			return HttpResponseRedirect('/SDP/instructor')

	course = Course(name=cname,course_detail=des,status='DR',category=Category.objects.get(pk=int(cat)),instructor=request.user)
	course.save()

	module = Module(name=mname,sequence=1,course=course)
	module.save()

	return HttpResponseRedirect('/SDP/instructor')

@login_required(login_url='/SDP/login')
@permission_required('SDP.instructor')
def addnewComponent(request,module_id):
	cname = request.POST.get('n-name')
	typ = request.POST.get('type')
	cont = request.POST.get('content')
	if typ == "VD":
		print("angad")
		cont = cont.replace("watch?v=", "v/")
	if((cname=="")and(typ=="")and(cont=="")):
			return HttpResponseRedirect('/SDP/instructor/ins-course/'+str(md.course.id)+'/1')

	md = Module.objects.get(pk=module_id)
	s = Component.objects.filter(module=md).aggregate(Max('sequence'))['sequence__max']
	if(not s):
		s=0
	component = Component(name=cname,typ=typ,module=md,content=cont,sequence=(s+1)) 
	component.save()

	return HttpResponseRedirect('/SDP/instructor/ins-course/'+str(md.course.id)+'/'+str(md.sequence))

@login_required(login_url='/SDP/login')
@permission_required('SDP.instructor')
def editcoursename(request,course_id):
	cname = request.POST.get('newCourseName')
	course = Course.objects.get(pk=course_id)
	course.name=cname
	course.save()
	return HttpResponseRedirect('/SDP/instructor/ins-course/'+str(course_id)+'/1')

@login_required(login_url='/SDP/login')
@permission_required('SDP.instructor')
def editcoursedesc(request,course_id):
	cname = request.POST.get('newCourseDesc')
	course = Course.objects.get(pk=course_id)
	course.course_detail = cname
	course.save()
	return HttpResponseRedirect('/SDP/instructor/ins-course/'+str(course_id)+'/1')

@login_required(login_url='/SDP/login')
@permission_required('SDP.instructor')
def editcoursecat(request,course_id):
	cname = request.POST.get('cat')
	course = Course.objects.get(pk=course_id)
	course.category = Category.objects.get(pk=int(cname))
	course.save()
	return HttpResponseRedirect('/SDP/instructor/ins-course/'+str(course_id)+'/1')

@login_required(login_url='/SDP/login')
@permission_required('SDP.instructor')
def editmodule(request,module_id):
	cname = request.POST.get('editModuleName')
	module = Module.objects.get(pk=module_id)
	module.name= cname
	module.save()
	return HttpResponseRedirect('/SDP/instructor/ins-course/'+str(module.course.id)+'/'+str(module.sequence))

@login_required(login_url='/SDP/login')
@permission_required('SDP.instructor')
def editcomponent(request,component_id):
	cname = request.POST.get('n')
	ccontent = request.POST.get('editcontent')
	component = Component.objects.get(pk=component_id)
	component.name=cname
	component.content = ccontent
	component.save()
	return HttpResponseRedirect('/SDP/instructor/ins-course/'+str(component.module.course.id)+'/'+str(component.module.sequence))
	
@login_required(login_url='/SDP/login')
def mycourse(request, course_id, module_id):
	template = loader.get_template('mycourse.html')
	user = request.user

	cpm = CourseParticipantMap.objects.filter(participant=user)
	if not cpm:
		return HttpResponse(template.render({}, request))
	cpm = CourseParticipantMap.objects.filter(participant=user).filter(progress__gt=-1)
	if not cpm:
		return HttpResponse(template.render({}, request))
	cpm = CourseParticipantMap.objects.filter(participant=user).get(progress__gt=-1)
	if course_id == "0":
		course_id = cpm.course.id
	mid = cpm.progress
	mm = Module.objects.filter(course = course_id).get(pk=mid)
	if module_id == "0":	
		module_id = Module.objects.filter(course=cpm.course).get(sequence=1).id
	try:
		c = Course.objects.get(pk=course_id)
	except c.DoesNotExist:
		raise Http404("Course does not exist")
	ms = Module.objects.filter(course=course_id).filter(sequence__lte=mm.sequence).order_by('sequence')
	try:
		m = Module.objects.filter(course=course_id).get(pk=module_id)
	except m.DoesNotExist:
		raise Http404("Module does not exist")
	co = Component.objects.filter(module=module_id).order_by('sequence')
	context = {
		'mycourse': c,
		'moduleset': ms,
		'module': m,
		'componentset': co,
	}
	return HttpResponse(template.render(context, request))

@login_required(login_url='/SDP/login')
def history(request, course_id, module_id):
	template = loader.get_template('history.html')
	user = request.user

	cpm = CourseParticipantMap.objects.filter(participant=user).filter(progress=-1).all()
	clist = []
	if not cpm:
		return HttpResponse(template.render({}, request))
	for ma in cpm:
		clist.append(ma.course.id)
	h = Course.objects.all().filter(pk__in=clist)
	if course_id == "0":
		return HttpResponse(template.render({'history': h,}, request))

	try:
		c = Course.objects.get(pk=course_id)
	except c.DoesNotExist:
		raise Http404("Course does not exist")

SDP/templates/base.html
<!-- jQuery -->
    <script src="../vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="../vendor/metisMenu/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="../dist/js/sb-admin-2.js"></script>

SDP/templates/form.html
<head>
<!-- Bootstrap Core CSS -->
    <link href="http://i.cs.hku.hk/~kpng/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="http://i.cs.hku.hk/~kpng/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="http://i.cs.hku.hk/~kpng/vendor/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://i.cs.hku.hk/~kpng/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
</head>
{% load crispy_forms_tags %}

{% block head_extra %}
{{ form.media }}

{% endblock head_extra %}
{% block content %}

{% if user.is_authenticated %}
already logged in
{%else%}
<div class=' col-sm-6 col-sm-offset-3'>
<h1>{{ title }}</h1>
<hr/>
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
{{ form|crispy }} 
<input type='submit' value="{{ title }} ">
</form>
{% if title == "Login" %}
<button><a href="/register" id='{{ title }}'>Register</a></button>
{% endif %}
</div>
{% endif %}
{% endblock content %}

 <!-- jQuery -->
    <script src="http://i.cs.hku.hk/~kpng/vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="http://i.cs.hku.hk/~kpng/vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="http://i.cs.hku.hk/~kpng/vendor/metisMenu/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="http://i.cs.hku.hk/~kpng/vendor/dist/js/sb-admin-2.js"></script>

SDP/templates/history.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SDP - History</title>

   <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static 'vendor/metisMenu/metisMenu.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'dist/css/sb-admin-2.css' %}" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="{% static 'vendor/morrisjs/morris.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript">
        function search(){
            var str = document.getElementById('searchstr');
            alert(str);
        }
        function course(){
            $http.get("/SDP/mycourse/0/module/0/");
        }
        function retake(courseid){
            if(!courseid) return false;
            var c = confirm("Are you sure to retake this course?");
            if(c==true){
                $.ajax({
                    url: "/SDP/retake/"+courseid+"/",
                    type: 'get',
                    success: function(result){
                        if(result=='success'){ 
                            alert('You have retaken the course successfully'); 
                            location.reload();
                        }else{
                            alert('Failed to retake this course: '+result);
                        }
                    }
                });
            }
        }
        function enroll(){

        }
    </script>

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <span class="navbar-brand" href="">SDP - Participant</span>
            </div>
            <!-- /.navbar-header -->
            

           <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                            <li><a href="/SDP/mycourse/0/module/0/">My Course</a></li>
                        <li><a href="/SDP/enroll/0/">Enroll</a></li>
                        <li><a href='/SDP/logout'>Logout</a></li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        {% if history %}

                        {% for course in history %}
                        <!-- Classes -->
                        <li>
                            <a href=""><i class="fa fa-table fa-fw"></i> {{course.name}}<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                            <!-- Modules -->
                            {% for module in course.module_set.all %}
                                <li>
                                    <a href="/SDP/history/{{course.id}}/module/{{module.id}}/">{{module.name}}</a>
                                </li>
                            {% endfor %}
                            </ul>
                        </li>
                        {% endfor %}
                        <br>
                        <br>
                        <p class="text-primary">
                            &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Status: Completed
                        </p>
                        <br>
                        <br>
                        <button class="btn btn-outline btn-primary btn-block" onclick="retake({{course.id}})">Retake This Course</button>
                        {% endif %}
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
        
        {% if module %}
            <span id="courseid" hidden="true">{{module.course}}</span>
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">{{module.name}}</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            {% for component in componentset %}
            {% if component.typ == 'TX' %}
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <h3 class="page-header">{{component.name}}</h3>
                </div>
                <div class="col-lg-12">
                {{component.content}}
                </div>
            </div>
            {% endif %}
            {% if component.typ == 'IM' %}
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <h3 class="page-header">{{component.name}}</h3>
                </div>
                <img src="{{component.content}}" width="100%"" max-width="600px" height="100%" max-height="600px">
            </div>
            {% endif %}
            {% if component.typ == 'VD' %}
            <div class="row">
                <div class="col-lg-12">
                    <h3 class="page-header">{{component.name}}</h3>
                </div>
                <iframe src="{{component.content}}" width="900px" height="600px" frameborder="0" allowfullscreen>
                </iframe>
            </div>
            {% endif %}
            {% if component.typ == 'FL' %}
            <div class="row">
                <div class="col-lg-12">
                    <h3 class="page-header">{{component.name}}</h3>
                </div>
                <p style="font-size:20px" class="fa fa-files-o"><a href="{{component.content}}"> View File</a></p>
            </div>
            {% endif %}
            {% endfor %}
        {% else %}
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">View History</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
        {% endif %}
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- /#wrapper -->
     <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static 'vendor/metisMenu/metisMenu.min.js' %}"></script>

    <!-- Morris Charts JavaScript -->
    <script src="{% static 'vendor/raphael/raphael.min.js' %}"></script>
    <script src="{% static 'vendor/morrisjs/morris.min.js' %}"></script>
    <script src="{% static 'data/morris-data.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'dist/js/sb-admin-2.js' %}"></script>

</body>

</html>